### ISSUE TITLE
Investigate use of Boost.Range

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/boost_graph_cookbook_1#33]
Here is the thread:

https://www.reddit.com/r/cpp/comments/3xw5q0/a_wellconnected_c11_boostgraph_tutorial/

From danieljh:
- Regarding the vertices and edges functions: I enjoy using Boost.Range with them, as they return a pair of first,last-iterators. Combining this with range adaptors and lambdas, Boost.Graph code can get really modern and readable, such as:

```
auto weights = edges(graph) | transformed(to_weights) | filtered(is_non_negative);
```

**Comment by daniel-j-h** [comment]
Hey hey, I just found your repository! Thumbs up for high quality documentation on bgl!

Here are a few snippets I'll be using in the context of bgl and coroutines. They show not only how to use ranges and adaptors but in addition a few other concepts, such as the csr graph (static graph), property maps, visitors and a couple of algorithms:

https://github.com/daniel-j-h/cppnow2016

Note: work in progress, will see some changes in the week to come.
Also: shameless plug https://cppnow2016.sched.org/event/6Sg3/pulling-visitors :)

**Comment by richelbilderbeek** [comment]
Hi @daniel-j-h, I look forward to watching your C++Now 2016 talk! 

Afterwards, I will probably add your stuff (*). But feel free to add/modify chapters. Most of the tutorial is about building up graphs and measuring basic stuff now. I'd love to have more of the niftier functions in!

(*) with your permission, I will attribute your work properly

**Comment by daniel-j-h** [comment]
> (*) with your permission, I will attribute your work properly

Sure feel free to do so, that's the reason it's open source after all! :)

**Comment by richelbilderbeek** [comment]
How did the talk at C++Now go? And, do you happen to know where the video can be viewed?

**Comment by daniel-j-h** [comment]
It usually takes a couple of weeks / months. In the meantime, check out the examples and slides at

https://github.com/daniel-j-h/cppnow2016

**Comment by richelbilderbeek** [comment]
Note to self: talk is posted [here](https://www.youtube.com/watch?v=3SvkWY7JSeY)

**Comment by richelbilderbeek** [comment]
Hi @daniel-j-h, currently I feel:

 * Yes, I think Boost.Range is fine
 * No, I do not think Boost.Range should be in this Cookbook as I prefer the algorithms to use only STL and Boost.Graph

When ranges are added to the STL, I may use that.

Sorry to maybe disappoint, but I need to draw a line somewhere, Your awesome library is just behind that line :rainbow: 

Will close this Issue :+1:
