### ISSUE TITLE
Add is_directed and is_undirected to test case of graph creation

### ISSUE THREAD

**Issue by mywtfmp3** [richelbilderbeek/boost_graph_cookbook_1#70]
The first two alogorithm create a directed graph and an undirected graph. The test case is simply,

```cpp
BOOST_AUTO_TEST_CASE( test_create_empty_directed_graph )
{
  const auto g = create_empty_directed_graph ( ) ;
}
```

Maybe we can add a test to check if the graph is directed in this case. Given a graph `g`, we can call `boost::is_directed(g)` to check if `g` is directed graph.

For example,

```cpp
BOOST_AUTO_TEST_CASE( test_create_empty_directed_graph )
{
  const auto g = create_empty_directed_graph ( ) ;
  BOOST_CHECK(boost::is_directed(g));
}
```

The same goes for undirected graph.

**Comment by richelbilderbeek** [comment]
I completely agree and did not knew that those functions existed! Will add, if you aren't first :+1:

**Comment by mywtfmp3** [comment]
Add it to demo or testcase? I think it should be test case?

**Comment by richelbilderbeek** [comment]
I would personally love to see it at both places.
