### ISSUE TITLE
std::ifstream can be constructed directly from std::string

### ISSUE THREAD

**Issue by mywtfmp3** [richelbilderbeek/boost_graph_cookbook_1#73]
```C++
std::string dot_filename;
std::ifstream f(dot_filename.c_str());
```

Found in *Algorithm 57 Loading a directed graph from a .dot file*. `ifstream` can be constructed from std::string (since C++ 11).

```C++
explicit basic_ifstream( const std::string& filename,
                         std::ios_base::openmode mode = ios_base::in );
```

**Comment by richelbilderbeek** [comment]
Well spotted! For this example, I have no idea why I chose not to do so. Will take a look at this on Friday. But feel encouraged to fix if you want to have it fixed sooner :+1:
