### ISSUE TITLE
Add to tutorial

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/boost_graph_cookbook_1#75]
I added some function that must be checked to be documented:

 * [x] add_bundled_edge_between_vertices 
 * [x] set_my_bundled_edge

**Comment by mywtfmp3** [comment]
Do you want a chatroom for discussions? Github issue tracker is not good for instant message. 

I created one here. https://gitter.im/boost-graph-cookbook

I am working on breath first search algorithm(just the program and comments), and I need your help to review it.

**Comment by richelbilderbeek** [comment]
No, I do not want to go into a chatroom, as it makes me lose focus. Just use Issues and I will read these when I can lose focus.
