### ISSUE TITLE
Use clang-format to format our code

### ISSUE THREAD

**Issue by mywtfmp3** [richelbilderbeek/boost_graph_cookbook_1#76]
Use clang-format so that we have a consistent coding style.

This is my `.clang-format`. Do you think it's appropriate?

https://gist.github.com/mywtfmp3/537ef6a9761239205b13f888092a332d

**Comment by richelbilderbeek** [comment]
Using clang-format is a great idea! To attribute this idea to you, I suggest you add this file using a commit or Pull Request. Then I can also see what its effects are.

Could you add this file?

**Comment by mywtfmp3** [comment]
Can you try it before I push this file? I am not sure whether you like the format.

To use it, 

1. Download the file and name it as `.clang-format`.
2. Place it in the same directory as your`example.cpp` file or its parent directory
3. run `clang-format example.cpp`, it will output a formatted file in the console. Or run `clang-format -i example.cpp`, it will format the file in place.

**Comment by richelbilderbeek** [comment]
Blimey, this is awesome! I will run `clang-format` on all code using that format. Thanks!

**Comment by richelbilderbeek** [comment]
Accepted the file without modification and applied it to all the `.cpp`, `.h` and `.impl` files.
